name: Deploy

on:
  push:
    branches: [ master, staging ]

jobs:
  deploy:
    uses: mia-mat/.github/.github/workflows/poseidon-deploy.yml@master
    secrets: inherit
    permissions:
      contents: read
      packages: write